#!/usr/bin/env python3
"""Generate Typer command stubs from NoCFO OpenAPI spec."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import httpx

OPENAPI_URL = "https://api-prd.nocfo.io/openapi/"
SRC_DIR = Path(__file__).resolve().parents[1] / "src"
sys.path.insert(0, str(SRC_DIR))

OUT_DIR = (
    Path(__file__).resolve().parents[1] / "src" / "nocfo_toolkit" / "cli" / "commands"
)
HEADER = "# This file is auto-generated by scripts/generate_cli_commands.py.\n"


def _to_snake_case(value: str) -> str:
    value = re.sub(r"[^a-zA-Z0-9]+", "_", value).strip("_")
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", value).lower() or "generated"


def _extract_groups(spec: dict) -> dict[str, list[tuple[str, str, str]]]:
    from nocfo_toolkit.openapi import filter_mcp_spec

    filtered_spec = filter_mcp_spec(spec, mcp_tag="MCP")
    groups: dict[str, list[tuple[str, str, str]]] = {}
    for path, methods in filtered_spec.get("paths", {}).items():
        if not isinstance(methods, dict):
            continue
        for method, meta in methods.items():
            if method.upper() not in {"GET", "POST", "PATCH", "PUT", "DELETE"}:
                continue
            tags = meta.get("tags", [])
            group = _to_snake_case(tags[0] if tags else "general")
            operation_id = meta.get("operationId") or f"{method}_{path}"
            command_name = _to_snake_case(operation_id.split("__")[0])
            groups.setdefault(group, []).append((command_name, method.upper(), path))
    return groups


def _write_group(group: str, commands: list[tuple[str, str, str]]) -> None:
    path = OUT_DIR / f"{group}.py"
    lines = [
        HEADER,
        '"""Auto-generated command stubs."""',
        "",
        "import typer",
        "",
        'app = typer.Typer(help="Auto-generated NoCFO command group")',
        "",
    ]
    for command_name, method, endpoint in sorted(commands):
        lines.extend(
            [
                f"@app.command(name={json.dumps(command_name)})",
                f"def {command_name}() -> None:",
                f'    """{method} {endpoint}"""',
                '    typer.echo("TODO: implement command logic")',
                "",
            ]
        )
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    response = httpx.get(OPENAPI_URL, timeout=60.0)
    response.raise_for_status()
    spec = response.json()
    groups = _extract_groups(spec)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for group, commands in groups.items():
        _write_group(group, commands)
    print(f"Generated {len(groups)} command group file(s) into {OUT_DIR}")


if __name__ == "__main__":
    main()
